bind 0.0.0.0
protected-mode yes
port 6379
tcp-backlog 511
timeout 0
tcp-keepalive 300

dir /data
appendonly yes
appendfsync everysec
save 3600 1
save 300 100
save 60 10000

maxmemory-policy noeviction

rename-command FLUSHALL ""
rename-command FLUSHDB ""
